### PR TITLE
adding flexbox support for layout

### LINKED ISSUE #62: Turn on flexbox support
See: http://v4-alpha.getbootstrap.com/getting-started/flexbox/

### PR DESCRIPTION
**Pull request by gvn**
Closes #62

### CODE REVIEW

**Comment by gvn** [comment]
Pretty small tweak, but without it the layout engine uses floats instead of flexbox. Gross! :see_no_evil:

**Comment by xmatthewx** [comment]
Gross! Lol'd for real.

**Comment by vazquez** [comment]
R+!

**Comment by gvn** [comment]
Yay!

**Pull request merged**
